### ISSUE TITLE
The regex `\u{0}` mutates to invalid syntax in node 18

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/weapon-regex#163]
Hi guys 🙋‍♂️, how is it going?

The regex `\u{0}` results in an invalid regex:

```diff
- /\u{0}/
+ /\u/
```

The name of the mutation is "Quantifier removal". However, this isn't a quantifier in this context, but rather the unicode character `0`. In node 16, this was silently ignored, however in the latest major release of node (v18) this results in a syntax error during the initial test run (dry run).

Originally reported here: https://github.com/stryker-mutator/stryker-js/issues/3579

![image](https://user-images.githubusercontent.com/1828233/175408204-bfab580c-238e-4f50-a6f4-82c789255b9a.png)

**Comment by Nhaajt** [comment]
Is this a node only thing? I just checked the latest [ECMAScript specification](https://tc39.es/ecma262/multipage/text-processing.html#prod-QuantifierPrefix) and `\u{0}` is a valid quantifier.

**Comment by nicojs** [comment]
Isn't `\u` a 'HexLeadSurrogate"?

https://tc39.es/ecma262/#sec-text-processing

In which case, the `{0}` should be a "HexTailDurrogate", not a quantifier

**Comment by Nhaajt** [comment]
To my understanding, `\u{0}` matches a hex escape sequence and `\u` alone is invalid only in Unicode mode with the `u` flag.

Otherwise, without the `u` flag, `\u` is an character identity escape that matches the character `u` and `\u{0}` matches it exactly zero times.

**Comment by nicojs** [comment]
Ahh yes, I see what you mean. I did some tests. Here `nvm` refers to the "node version manager", a simple way to install and use different versions of node:

<details>
  <summary>See tests I did</summary>
  
```
nicojs@NicoJ01 ~ $ cat main.js
function foo() {
   const re = /\u/;
}
console.log('done');
nicojs@NicoJ01 ~ $ nvm use 18
Now using node v18.4.0 (npm v8.12.1)
nicojs@NicoJ01 ~ $ node main.js
done
nicojs@NicoJ01 ~ $ cat main-unicode.js
function foo() {
   const re = /\u/u;
}
console.log('done');
nicojs@NicoJ01 ~ $ node main-unicode.js
/home/nicojs/main-unicode.js:2
   const re = /\u/u;
              ^^^^^

SyntaxError: Invalid regular expression: /\u/: Invalid Unicode escape
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1040:15)
    at Module._compile (node:internal/modules/cjs/loader:1076:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.4.0
nicojs@NicoJ01 ~ $ nvm use 16
Now using node v16.15.0 (npm v8.5.5)
nicojs@NicoJ01 ~ $ node main-unicode.js
done
nicojs@NicoJ01 ~ $
```
</details>

I now see that in the original issue `gu` was used as flags: `/\u{0}/gu`. 

As far as I can see [\u is the only flag that changes the actual parsing of the regex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_flags). It might be best to add a new parsing flavor for this: `JSUnicode`. Then StrykerJS can use that flavor when it sees a unicode flag. 🤷‍♂️

**Comment by Nhaajt** [comment]
I spent a little bit of time looking through the grammar of the JS regex from ECMAScript and it _seems_ like only the `u` flag affects the parsing. So, we can either have:
1. flags as an inputtable parameter and check for the `u` flag during parsing within the same parsing flavor
2. a new parsing flavor `JSUnicode` as you suggested

Which one do you prefer? In any case, I found out that the `u` flag affects more than just `\u`. For example, with the `u` flag:
- `\u` marks the start of a Unicode escape sequence, otherwise it matches the character `u`
- `\p{UnicodeProperty}` matches a Unicode property escape, otherwise it matches the character `p` followed by the string `{UnicodeProperty}`
- a character identity escape `\x` is only valid if `x` is a syntax character `^ $ \ . * + ? ( ) [ ] { } |` or `/`. Without the `u` flag, a character identity escape accepts other characters (that’s why `\u` in this case is valid)

**Comment by nicojs** [comment]
Both would work for us. During mutating StrykerJS has access to the `flags` property, which is just a string containing all flags. We could pass that along, or we could see if `u` is included and based on that choose the correct flavor.

![image](https://user-images.githubusercontent.com/1828233/175770869-8f5a712b-596d-4add-84c2-6313f30da69a.png)

What would you guys prefer? Both are fine by me. I feel like passing flags might be a bit more future-proof in the end.

**Comment by ericcornelissen** [comment]
Hi :wave: I'm the one that created the original bug report in stryker-js. I decided to give implementing this a try (even though I have little experience with Scala). Please see [my changes](https://github.com/stryker-mutator/weapon-regex/compare/main...ericcornelissen:weapon-regex:feat/js-unicode) and let me know if it's heading in the right direction - if yes I'd like to try and finish the contribution :slightly_smiling_face: 

One comment regarding my changes, I decided to go with the _"a new parsing flavor JSUnicode"_ suggestion as it wasn't quite clear to me how the flag could/should be added as an inputtable parameter - even though I agree with the comment that "I feel like passing flags might be a bit more future-proof in the end."

**Comment by Nhaajt** [comment]
@nicojs I agree with you that supporting JS flags is more future-proof, so I went with it. Interface wise, now you can do this:
```js
mutate(pattern, flags, mutationOptions); // new
mutate(pattern, mutationOptions);        // still works
```
You can check it out in the [`feat/parser-js-flags` branch](https://github.com/stryker-mutator/weapon-regex/tree/feat/parser-js-flags) and tell me what you think.

---

@ericcornelissen Thanks you for taking interest in our little project ❤

I’m also working on a fix for this by adding support for parsing JS flags. It took a bit of time to iron out all the little cases. You can check it out in the [`feat/parser-js-flags` branch](https://github.com/stryker-mutator/weapon-regex/tree/feat/parser-js-flags).

**Comment by nicojs** [comment]
Wow, you're working fast as always! 🤟

I've created a draft PR so I could leave a comment inside the code here: https://github.com/stryker-mutator/weapon-regex/pull/165

**Comment by ericcornelissen** [comment]
> I’m also working on a fix for this by adding support for parsing JS flags. It took a bit of time to iron out all the little cases. You can check it out in the [feat/parser-js-flags branch](https://github.com/stryker-mutator/weapon-regex/tree/feat/parser-js-flags).

Cool! Looks like you're much further along so let's go with that :smiley: :+1: 

> I've created a draft PR so I could leave a comment inside the code here: https://github.com/stryker-mutator/weapon-regex/pull/165

I added a review as well :slightly_smiling_face:
