### ISSUE TITLE
Chinese regular expressions

### ISSUE THREAD

**Issue by vcejudo** [stryker-mutator/weapon-regex#248]
Hi!
Sorry to raise a question (more than a bug).
I was running Stryker with production code with a regular expression like this - as I need to do something specific with Chinese characters.:

```
const findChineseCharacter = /\p{Script_Extensions=Han}/gu;
```

So, when running Stryker I got:

```
[RegexMutator]: The Regex parser of weapon-regex couldn't parse this regex pattern: "\p{Script_Extensions=Han}". Please report this issue at https://github.com/stryker-mutator/weapon-regex/issues. Inner error: [Error] Parser: Position 1:1, found "\\p{Script_"
```

It's not very important, but that's definitely part of the regular expression of Typescript regular expressions as this entry points out: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape

Note that Java has a quite different way to handle Chinese in regular expressions.

**Comment by nhaajt** [comment]
The parsing error was caused by weapon-regex not being able to parse Unicode character classes with property and value `\p{property=value}`, which should be now supported with #249
