### ISSUE TITLE
/foo|/ not supported

### ISSUE THREAD

**Issue by regseb** [stryker-mutator/weapon-regex#32]
> [RegexMutator]: The Regex parser of weapon-regex couldn't parse this regex pattern: "^(\\\*|[^:]+):\\/\\/(\\\*|(?:\\\*\\.)?[^/\*]+|)\\/(.\*)$". Please report this issue at https://github.com/stryker-mutator/weapon-regex/issues. Inner error: [Error] Parser: Position 1:17, found "(\\\\\*|(?:\\\\\*\\\\"

This is a [regex used](https://github.com/regseb/castkodi/blob/master/src/tools/matchpattern.js#L30) to parse [match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns). I think it's the `|` with nothing that isn't supported because the regex `/foo|/` shows the same error.

**Comment by wijtserekker** [comment]
Thank you for pointing this out! It is indeed the `|` with nothing to the right that is not supported yet. We'll make sure that this will be supported in the future.
