### ISSUE TITLE
Unparsable but valid regex

### ISSUE THREAD

**Issue by jamesrweb** [stryker-mutator/weapon-regex#34]
## Error

> [RegexMutator]: The Regex parser of weapon-regex couldn't parse this regex pattern: "mini-css-extract-plugin[^]*Conflicting order between:". Please report this issue at https://github.com/stryker-mutator/weapon-regex/issues. Inner error: [Error] Parser: Position 1:24, found "[^]*Confli"

## Regex

`/mini-css-extract-plugin[^]*Conflicting order between:/`

This is a valid regex though and works as expected so not sure why it is unparseable?

**Comment by wijtserekker** [comment]
Thank you for pointing this out! After a quick search I found out that we are not yet able to parse an empty character class (`[]` or `[^]`), while this is possible in JS regexes. We will add this in a future release.
